# Measure analysis

##### Imports and params

In [1]:
from __future__ import annotations

import pandas as pd

from pathlib import Path
import matplotlib.pyplot as plt

In [2]:
plt.rcParams.update({
"figure.figsize": (18, 10),
"axes.grid": True,
"grid.linestyle": ":",
"grid.alpha": 0.5,
"axes.titlesize": 14,
"axes.labelsize": 12,
"legend.fontsize": 10,
})

In [3]:
MORPHO_RESULTS = Path("/home/loai/Documents/code/RSMLExtraction/RSA_reconstruction/Method/ChronoRoot/GLOBAL_MORPHOLOGY.csv").expanduser()
DYNAMIC_RESULTS = Path("/home/loai/Documents/code/RSMLExtraction/RSA_reconstruction/Method/ChronoRoot/GLOBAL_DYNAMICS.csv").expanduser()
GT_MORPHO_RESULTS = Path("/home/loai/Documents/code/RSMLExtraction/RSA_reconstruction/Method/ChronoRoot/Ground_truth_root.csv").expanduser()
PATH_2_LOGS = Path("/home/loai/Documents/code/RSMLExtraction/RSA_reconstruction/Method/ChronoRoot/all_events_combined.csv").expanduser()

## Loading database

In [4]:
df_plant_morpho = pd.read_csv(MORPHO_RESULTS)

df_plant_morpho = df_plant_morpho.drop(columns=["FileName"])

# order by box_name, img_num, plant_num, Time elapsed (hours)
df_plant_morpho = df_plant_morpho.sort_values(by=["box_name", "img_num", "plant_num", "Time elapsed (hours)"])

df_plant_morpho.head()

,box_name,loss_name,epoch,img_num,plant_num,TimeStep,MainRootLength,LateralRootsLength,NumberOfLateralRoots,TotalLength,TotalOrganCount,ConvexHullArea,RootDensity,Time elapsed (hours),Acquisition Time
3459,rpi14_2020-01-08_17-25,CLDICE,5,1,2,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
11504,rpi14_2020-01-08_17-25,CLDICE,125,1,2,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
22504,rpi14_2020-01-08_17-25,CLDICE,130,1,2,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
34072,rpi14_2020-01-08_17-25,CLDICE,70,1,2,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
45431,rpi14_2020-01-08_17-25,CLDICE,155,1,2,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0

In [5]:
time_step_hours = df_plant_morpho['Time elapsed (hours)'].diff().loc[df_plant_morpho['Time elapsed (hours)'].diff() > 0].median()
print(f"Intervalle détecté entre les images : {time_step_hours} heures (soit {time_step_hours*60} min)")

Intervalle détecté entre les images : 0.25 heures (soit 15.0 min)

In [6]:
df_plant_dynamics = pd.read_csv(DYNAMIC_RESULTS)

df_plant_dynamics = df_plant_dynamics.drop(columns=["newDay"])

df_plant_dynamics['Time elapsed (hours)'] = df_plant_dynamics['Time'] * 4 * time_step_hours

# order by box_name, img_num, plant_num, time
df_plant_dynamics = df_plant_dynamics.sort_values(by=["box_name", "img_num", "plant_num", "Time"])

cols = ['box_name', 'img_num', 'plant_num', 'Time elapsed (hours)']
cols += [c for c in df_plant_dynamics.columns if c not in cols]
df_plant_dynamics = df_plant_dynamics[cols]

df_plant_dynamics

,box_name,img_num,plant_num,Time elapsed (hours),loss_name,epoch,Time,mainRootLength,lateralRootsLength,totalRootsLength,...,totalRootsGrad,mainRootAccel,lateralRootsAccel,totalRootsAccel,NumberOfLateralRoots,ConvexHullArea,RootDensity,mainOverTotal,lateralRootDensity,lateralRootContDensity
864,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,5,0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
2874,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,125,0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
5621,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,130,0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
8510,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,70,0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
11346,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,155,0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629752,rpi15_2020-03-12_17-01,4,4,454.0,CLDICE,20,454,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
691265,rpi15_2020-03-12_17-01,4,4,454.0,BCE,35,454,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
716484,rpi15_2020-03-12_17-01,4,4,454.0,BCE,60,454,36.714560,8.219697,44.934257,...,0.000000,0.000000,0.0,0.000000,3.00,33.61456,1.262540,81.691780,0.817115,0.223881
734768,rpi15_2020-03-12_17-01,4,4,454.0,BCE,20,454,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.00,0.00000,0.000000,100.000000,0.000000,0.000000
751108,rpi15_2020-03-12_17-01,4,4,454.0,BCE,45,454,29.968659,5.150092,35.118752,...,0.101607,4.612312,0.0,4.612312,0.75,20.93072,0.898435,85.335207,0.250261,0.144108

In [7]:
df_ground_truth = pd.read_csv(GT_MORPHO_RESULTS)
df_ground_truth = df_ground_truth.drop(columns=["FileName"])


df_ground_truth = df_ground_truth.sort_values(by=["box_name", "img_num", "plant_num", "Time elapsed (hours)"])

df_ground_truth

,box_name,img_num,plant_num,TimeStep,TotalRootLength,LateralRootLength,NumberOfLateralRoots,mainRootGrad,mainRootAccel,lateralRootsGrad,lateralRootsAccel,totalRootsGrad,totalRootsAccel,NumberOfOrgans,Convex_Area_Hull,RootDensity,Time elapsed (hours),Acquisition Time,PrimaryRootLength
9596,rpi14_2020-01-08_17-25,1,1,429,1.793137,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0576,31.130852,107.250000,11.15,1.793137
9597,rpi14_2020-01-08_17-25,1,1,430,1.889706,0.000000,0.0,0.386274,NaN,0.000000,NaN,0.386274,NaN,1,0.0952,19.849849,107.500000,11.30,1.889706
9598,rpi14_2020-01-08_17-25,1,1,431,1.889706,0.000000,0.0,0.000000,-1.545097,0.000000,0.000000,0.000000,-1.545097,1,0.0960,19.684434,107.750000,11.45,1.889706
9599,rpi14_2020-01-08_17-25,1,1,432,1.833137,0.000000,0.0,-0.226274,-0.905097,0.000000,0.000000,-0.226274,-0.905097,1,0.0600,30.552285,108.000000,12.00,1.833137
9600,rpi14_2020-01-08_17-25,1,1,433,1.833137,0.000000,0.0,0.000000,0.905097,0.000000,0.000000,0.000000,0.905097,1,0.0592,30.965153,108.250000,12.15,1.833137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18199,rpi15_2020-03-12_17-01,4,4,1645,54.840167,18.278216,5.0,-0.386274,-1.545097,0.320000,3.620387,-0.066274,2.075290,6,190.1744,0.288368,412.250278,4.16,36.561951
18200,rpi15_2020-03-12_17-01,4,4,1646,55.136736,18.374785,5.0,0.800000,4.745097,0.386274,0.265097,1.186274,5.010193,6,192.0360,0.287117,412.500278,4.31,36.761951
18201,rpi15_2020-03-12_17-01,4,4,1647,55.249873,18.504491,5.0,-0.066348,-3.469246,0.519400,0.533094,0.453052,-2.936152,6,193.8416,0.285026,412.750000,4.46,36.745382
18202,rpi15_2020-03-12_17-01,4,4,1648,55.369873,18.584491,5.0,0.159822,0.903677,0.319645,-0.798132,0.479467,0.105545,6,193.2424,0.286531,413.000278,5.01,36.785382
18203,rpi15_2020-03-12_17-01,4,4,1649,55.376736,18.631354,6.0,-0.160178,-1.281425,0.187660,-0.528526,0.027482,-1.809951,7,192.5880,0.287540,413.250000,5.16,36.745382

In [8]:
cols_to_keep = ['step', 'value', 'folder', 'metric']
df_logs_tb = pd.read_csv(PATH_2_LOGS, usecols=lambda c: c in cols_to_keep)

df_logs_tb = df_logs_tb.rename(columns={"step": "epoch", "value": "model_metric_value"})


meta_data = df_logs_tb['folder'].str.split('/', expand=True)
df_logs_tb['model_name'] = meta_data[11]
df_logs_tb['loss_name'] = meta_data[10]

df_logs_tb = df_logs_tb[df_logs_tb['metric'] != 'batch_loss']

df_logs_tb = df_logs_tb.drop(columns=['folder'])
df_logs_tb.head()

           metric  model_metric_value  epoch model_name loss_name
10000  epoch_loss            0.335330      0    ResUNet    CLDICE
10001  epoch_loss            0.309060      1    ResUNet    CLDICE
10002  epoch_loss            0.294935      2    ResUNet    CLDICE
10003  epoch_loss            0.290948      3    ResUNet    CLDICE
10004  epoch_loss            0.286203      4    ResUNet    CLDICE

## Merge databases

In [9]:
subset_keys = ['epoch', 'loss_name', 'model_name', 'metric']


duplicates_mask = df_logs_tb.duplicated(subset=subset_keys, keep=False)
df_duplicates = df_logs_tb[duplicates_mask]

df_duplicates = df_duplicates.sort_values(by=subset_keys)

print(f"Nombre total de lignes dupliquées : {len(df_duplicates)}")
print("Aperçu des doublons :")
df_duplicates

Nombre total de lignes dupliquées : 28
Aperçu des doublons :

                   metric  model_metric_value  epoch model_name loss_name
27700          epoch_loss            0.239010      0     SegNet    CLDICE
37702          epoch_loss            0.193066      0     SegNet    CLDICE
27701       learning_rate            0.000100      0     SegNet    CLDICE
37902       learning_rate            0.000100      0     SegNet    CLDICE
39502         val_auc_gpu            0.823237      0     SegNet    CLDICE
41504         val_auc_gpu            0.513013      0     SegNet    CLDICE
39302        val_dice_gpu            0.992247      0     SegNet    CLDICE
41503        val_dice_gpu            0.992285      0     SegNet    CLDICE
38102            val_loss            0.033031      0     SegNet    CLDICE
41502            val_loss            0.094691      0     SegNet    CLDICE
39702   val_precision_gpu            0.060015      0     SegNet    CLDICE
41505   val_precision_gpu            0.000000      0     SegNet    CLDICE
39902      val_recall_gpu            0.000908      0     SegNet    CLDICE
41506      val_recall_gpu            0.000000      0     SegNet    CLDICE
175707         epoch_loss            0.253388      0     SegNet      DICE
176207         epoch_loss            0.206539      0     SegNet      DICE
175907      learning_rate            0.000100      0     SegNet      DICE
176208      learning_rate            0.000100      0     SegNet      DICE
177609        val_auc_gpu            0.643726      0     SegNet      DICE
179611        val_auc_gpu            0.712744      0     SegNet      DICE
177409       val_dice_gpu            0.988801      0     SegNet      DICE
179610       val_dice_gpu            0.992311      0     SegNet      DICE
176209           val_loss            0.062853      0     SegNet      DICE
179609           val_loss            0.077597      0     SegNet      DICE
177809  val_precision_gpu            0.018500      0     SegNet      DICE
179612  val_precision_gpu            0.021913      0     SegNet      DICE
178009     val_recall_gpu            0.016480      0     SegNet      DICE
179613     val_recall_gpu            0.000050      0     SegNet      DICE

In [10]:
df_logs_pivoted = df_logs_tb.pivot_table(
    index=['epoch', 'loss_name', 'model_name'], 
    columns='metric', 
    values='model_metric_value',
    aggfunc='first'  
).reset_index()
df_logs_pivoted.head()

metric,epoch,loss_name,model_name,epoch_loss,learning_rate,val_auc_gpu,val_betti_0_abs_err,val_betti_0_err,val_betti_1_abs_err,val_betti_1_err,...,val_f1,val_hausdorff_95,val_hausdorff_max,val_iou,val_loss,val_precision,val_precision_gpu,val_recall,val_recall_gpu,val_surface_dice_1mm
0,0,BCE,DeepLab,0.092989,0.0001,0.586677,4.036364,1.000000,49.545456,0.763636,...,0.000000,inf,inf,0.000000,0.023106,0.000000,0.000000,0.000000,0.000000,0.000000
1,0,BCE,ResUNet,0.335836,0.0001,0.863053,2350.672607,0.996358,2667.072754,0.964186,...,0.028216,40.694187,79.099243,0.014445,0.159749,0.014540,0.013997,0.817185,0.796151,0.209185
2,0,BCE,ResUNetDS,0.338226,0.0001,0.890586,2618.418213,0.996123,39.000000,0.536374,...,0.211534,52.859432,79.267410,0.122789,0.159186,0.132165,0.132760,0.783553,0.716365,0.295772
3,0,BCE,SegNet,0.184791,0.0001,0.771161,40.654545,0.992045,48.781818,0.757157,...,0.000000,inf,inf,0.000000,0.042060,0.000000,0.005513,0.000000,0.000008,0.000000
4,0,BCE,UNet,0.340405,0.0001,0.927975,2896.836426,0.996995,2953.600098,0.967826,...,0.030845,47.715458,79.255432,0.015829,0.158473,0.015879,0.015311,0.917735,0.895810,0.164464

In [11]:
df_morpho_log = pd.merge(
    df_plant_morpho, 
    df_logs_pivoted, 
    on=['epoch', 'loss_name'], 
    how='left'
)

df_morpho_log = df_morpho_log.dropna()

df_morpho_log.head()

,box_name,loss_name,epoch,img_num,plant_num,TimeStep,MainRootLength,LateralRootsLength,NumberOfLateralRoots,TotalLength,...,val_f1,val_hausdorff_95,val_hausdorff_max,val_iou,val_loss,val_precision,val_precision_gpu,val_recall,val_recall_gpu,val_surface_dice_1mm
0,rpi14_2020-01-08_17-25,CLDICE,5,1,2,0,0.0,0.0,0.0,0.0,...,0.000000,inf,inf,0.000000,0.016666,0.000000,0.000000,0.000000,0.000000,0.000000
1,rpi14_2020-01-08_17-25,CLDICE,5,1,2,0,0.0,0.0,0.0,0.0,...,0.311357,46.511993,63.311260,0.191934,0.140740,0.197049,0.061476,0.926819,0.753968,0.419494
2,rpi14_2020-01-08_17-25,CLDICE,5,1,2,0,0.0,0.0,0.0,0.0,...,0.401716,33.676563,48.961002,0.256251,0.130312,0.319031,0.070334,0.651047,0.657444,0.616471
3,rpi14_2020-01-08_17-25,CLDICE,5,1,2,0,0.0,0.0,0.0,0.0,...,0.417544,37.666084,53.476871,0.272756,0.013824,0.409649,0.423544,0.498318,0.239893,0.582952
4,rpi14_2020-01-08_17-25,CLDICE,5,1,2,0,0.0,0.0,0.0,0.0,...,0.261773,42.018467,61.970177,0.158736,0.135011,0.167126,0.131484,0.857901,0.504967,0.282735

In [12]:
df_dynamic_log = pd.merge(
    df_plant_dynamics, 
    df_logs_pivoted, 
    on=['epoch', 'loss_name'], 
    how='left'
)

df_dynamic_log = df_dynamic_log.dropna()

df_dynamic_log.head()

,box_name,img_num,plant_num,Time elapsed (hours),loss_name,epoch,Time,mainRootLength,lateralRootsLength,totalRootsLength,...,val_f1,val_hausdorff_95,val_hausdorff_max,val_iou,val_loss,val_precision,val_precision_gpu,val_recall,val_recall_gpu,val_surface_dice_1mm
0,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,5,0,0.0,0.0,0.0,...,0.000000,inf,inf,0.000000,0.016666,0.000000,0.000000,0.000000,0.000000,0.000000
1,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,5,0,0.0,0.0,0.0,...,0.311357,46.511993,63.311260,0.191934,0.140740,0.197049,0.061476,0.926819,0.753968,0.419494
2,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,5,0,0.0,0.0,0.0,...,0.401716,33.676563,48.961002,0.256251,0.130312,0.319031,0.070334,0.651047,0.657444,0.616471
3,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,5,0,0.0,0.0,0.0,...,0.417544,37.666084,53.476871,0.272756,0.013824,0.409649,0.423544,0.498318,0.239893,0.582952
4,rpi14_2020-01-08_17-25,1,2,0.0,CLDICE,5,0,0.0,0.0,0.0,...,0.261773,42.018467,61.970177,0.158736,0.135011,0.167126,0.131484,0.857901,0.504967,0.282735

## Visualize raw data

### Utils

In [13]:
import ipywidgets as widgets
from IPython.display import display

In [14]:
# List all loss names, model names, and metrics
loss_names = df_morpho_log['loss_name'].unique().tolist()
model_names = df_morpho_log['model_name'].unique().tolist()
col_box_name = df_morpho_log["box_name"].unique().tolist()
col_img_number = df_morpho_log["img_num"].unique().tolist()
col_plant_number = df_morpho_log["plant_num"].unique().tolist()
col_timestep = df_morpho_log["TimeStep"].unique().tolist()
col_timestep.sort()
col_time_hours = df_morpho_log['Time elapsed (hours)'].unique().tolist()
col_time_hours.sort()
col_acquired_time = df_morpho_log['Acquisition Time'].unique().tolist()
col_acquired_time.sort()
col_epoch = df_morpho_log["epoch"].unique().tolist()
col_epoch.sort()
img_metrics = df_logs_tb['metric'].unique().tolist()
plant_measures = df_plant_morpho.columns.tolist()
# remove everything that is not a measure
for col in ['epoch', 'loss_name', 'model_name', 'box_name', 'img_num', 'plant_num', 'TimeStep', 'FileName', 'Time elapsed (hours)', 'Acquisition Time']:
    if col in plant_measures:
        plant_measures.remove(col)
print("Available loss names:", loss_names)
print("Available model names:", model_names)
print("Available box names:", col_box_name)
print("Available image numbers:", col_img_number)
print("Available plant numbers:", col_plant_number)
print("Available time steps:", col_timestep)
print("Available epochs:", col_epoch)
print("Available image metrics:", img_metrics)
print("Available plant measures:", plant_measures)

Available loss names: ['CLDICE', 'BCE', 'DICE']
Available model names: ['DeepLab', 'ResUNet', 'ResUNetDS', 'SegNet', 'UNet']
Available box names: ['rpi14_2020-01-08_17-25', 'rpi14_2020-03-12_17-00', 'rpi15_2020-01-08_17-24', 'rpi15_2020-03-12_17-01']
Available image numbers: [1, 2, 3, 4]
Available plant numbers: [2, 3, 4, 1]
Available time steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823]
Available epochs: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195]
Available image metrics: ['epoch_loss', 'learning_rate', 'val_loss', 'val_f1', 'val_precision', 'val_recall', 'val_iou', 'val_dice', 'val_dice_gpu', 'val_auc_gpu', 'val_precision_gpu', 'val_recall_gpu', 'val_betti_0_err', 'val_betti_1_err', 'val_betti_0_abs_err', 'val_betti_1_abs_err', 'val_hausdorff_95', 'val_hausdorff_max', 'val_surface_dice_1mm']
Available plant measures: ['MainRootLength', 'LateralRootsLength', 'NumberOfLateralRoots', 'TotalLength', 'TotalOrganCount', 'ConvexHullArea', 'RootDensity']

In [15]:
# List all loss names, model names, and metrics
loss_names2 = df_dynamic_log['loss_name'].unique().tolist()
model_names2 = df_dynamic_log['model_name'].unique().tolist()
col_box_name2 = df_dynamic_log["box_name"].unique().tolist()
col_img_number2 = df_dynamic_log["img_num"].unique().tolist()
col_plant_number2 = df_dynamic_log["plant_num"].unique().tolist()
col_time2 = df_dynamic_log['Time'].unique().tolist()
col_time2.sort()
col_epoch2 = df_dynamic_log["epoch"].unique().tolist()
col_epoch2.sort()
img_metrics2 = df_logs_tb['metric'].unique().tolist()
plant_measures2 = df_plant_dynamics.columns.tolist()
# remove everything that is not a measure
for col in ['epoch', 'loss_name', 'model_name', 'box_name', 'img_num', 'plant_num', 'TimeStep', 'FileName', 'Time', 'Time elapsed (hours)', 'Acquisition Time']:
    if col in plant_measures2:
        plant_measures2.remove(col)
print("Available loss names:", loss_names2)
print("Available model names:", model_names2)
print("Available box names:", col_box_name2)
print("Available image numbers:", col_img_number2)
print("Available plant numbers:", col_plant_number2)
print("Available epochs:", col_epoch2)
print("Available image metrics:", img_metrics2)
print("Available plant measures:", plant_measures2)

Available loss names: ['CLDICE', 'BCE', 'DICE']
Available model names: ['DeepLab', 'ResUNet', 'ResUNetDS', 'SegNet', 'UNet']
Available box names: ['rpi14_2020-01-08_17-25', 'rpi14_2020-03-12_17-00', 'rpi15_2020-01-08_17-24', 'rpi15_2020-03-12_17-01']
Available image numbers: [1, 2, 3, 4]
Available plant numbers: [2, 3, 4, 1]
Available epochs: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195]
Available image metrics: ['epoch_loss', 'learning_rate', 'val_loss', 'val_f1', 'val_precision', 'val_recall', 'val_iou', 'val_dice', 'val_dice_gpu', 'val_auc_gpu', 'val_precision_gpu', 'val_recall_gpu', 'val_betti_0_err', 'val_betti_1_err', 'val_betti_0_abs_err', 'val_betti_1_abs_err', 'val_hausdorff_95', 'val_hausdorff_max', 'val_surface_dice_1mm']
Available plant measures: ['mainRootLength', 'lateralRootsLength', 'totalRootsLength', 'mainRootGrad', 'lateralRootsGrad', 'totalRootsGrad', 'mainRootAccel', 'lateralRootsAccel', 'totalRootsAccel', 'NumberOfLateralRoots', 'ConvexHullArea', 'RootDensity', 'mainOverTotal', 'lateralRootDensity', 'lateralRootContDensity']

### Visu

In [16]:
w_loss = widgets.Dropdown(options=df_morpho_log['loss_name'].unique(), description='Loss:')
w_epoch = widgets.IntSlider(min=df_morpho_log['epoch'].min(), max=df_morpho_log['epoch'].max(), step=5, description='Epoch:')
w_box = widgets.Dropdown(options=sorted(df_morpho_log['box_name'].unique()), description='Box:')
w_img_num = widgets.Dropdown(options=[], description='Img Num:')
w_plant_num = widgets.Dropdown(options=[], description='Plant Num:')
w_measure = widgets.Dropdown(options=plant_measures if 'plant_measures' in locals() else ['Length'], description='Measure:')


def update_dependent_options(*args):
    current_box = w_box.value
    
    subset = df_morpho_log[df_morpho_log['box_name'] == current_box]
    
    available_imgs = sorted(subset['img_num'].unique())
    w_img_num.options = available_imgs
    
    available_plants = sorted(subset['plant_num'].unique())
    w_plant_num.options = available_plants


w_box.observe(update_dependent_options, names='value')

update_dependent_options()

def plot_logic(loss_name, w_epoch, measure, box_name, img_num, plant_num):
    df_filtered = df_morpho_log[
        (df_morpho_log['loss_name'] == loss_name) &
        (df_morpho_log['epoch'] == w_epoch) &
        (df_morpho_log['img_num'] == img_num) &
        (df_morpho_log['box_name'] == box_name) &
        (df_morpho_log['plant_num'] == plant_num)
    ]
    
    df_filtered = df_filtered.sort_values('Time elapsed (hours)')

    plt.figure(figsize=(14, 6))
    
    plt.plot(df_filtered['Time elapsed (hours)'], df_filtered[measure], marker='o', color='green', label=measure, linewidth=2, markersize=3)
    plt.title(f'Morpho Measure: {measure}\n(Plant {plant_num})')
    plt.xlabel('Time (hours)')
    plt.legend()
    
    plt.tight_layout()
    plt.show()

ui = widgets.VBox([
    widgets.HBox([w_loss, w_epoch]),
    widgets.HBox([w_box, w_img_num, w_plant_num]),
    widgets.HBox([w_measure])
])

out = widgets.interactive_output(plot_logic, {
    'loss_name': w_loss,
    'w_epoch': w_epoch,
    'measure': w_measure,
    'box_name': w_box,
    'img_num': w_img_num,
    'plant_num': w_plant_num
})

display(ui, out)

VBox(children=(HBox(children=(Dropdown(description='Loss:', options=('CLDICE', 'BCE', 'DICE'), value='CLDICE')…

Output()

In [17]:
# same but for dynamics
w_loss2 = widgets.Dropdown(options=df_dynamic_log['loss_name'].unique(), description='Loss:')
w_epoch2 = widgets.IntSlider(min=df_dynamic_log['epoch'].min(), max=df_dynamic_log['epoch'].max(), step=5, description='Epoch:')
w_box2 = widgets.Dropdown(options=sorted(df_dynamic_log['box_name'].unique()), description='Box:')
w_img_num2 = widgets.Dropdown(options=[], description='Img Num:')
w_plant_num2 = widgets.Dropdown(options=[], description='Plant Num:')
w_measure2 = widgets.Dropdown(options=plant_measures2 if 'plant_measures2' in locals() else ['Length'], description='Measure:')

def update_dependent_options(*args):
    current_box = w_box2.value
    
    subset = df_dynamic_log[df_dynamic_log['box_name'] == current_box]
    
    available_imgs = sorted(subset['img_num'].unique())
    w_img_num2.options = available_imgs
    
    available_plants = sorted(subset['plant_num'].unique())
    w_plant_num2.options = available_plants
w_box2.observe(update_dependent_options, names='value')  
update_dependent_options()

def plot_logic(loss_name, w_epoch, measure, box_name, img_num, plant_num):
    df_filtered = df_dynamic_log[
        (df_dynamic_log['loss_name'] == loss_name) &
        (df_dynamic_log['epoch'] == w_epoch) &
        (df_dynamic_log['img_num'] == img_num) &
        (df_dynamic_log['box_name'] == box_name) &
        (df_dynamic_log['plant_num'] == plant_num)
    ]
    
    df_filtered = df_filtered.sort_values('Time')

    plt.figure(figsize=(14, 6))
    
    plt.plot(df_filtered['Time'], df_filtered[measure], marker='o', color='blue', label=measure, linewidth=2, markersize=3)
    plt.title(f'Dynamic Measure: {measure}\n(Plant {plant_num})')
    plt.xlabel('Time Step')
    plt.legend()
    
    plt.tight_layout()
    plt.show()
    
ui = widgets.VBox([
    widgets.HBox([w_loss2, w_epoch2]),
    widgets.HBox([w_box2, w_img_num2, w_plant_num2]),
    widgets.HBox([w_measure2])
])

out = widgets.interactive_output(plot_logic, {
    'loss_name': w_loss2,
    'w_epoch': w_epoch2,
    'measure': w_measure2,
    'box_name': w_box2,
    'img_num': w_img_num2,
    'plant_num': w_plant_num2
})

display(ui, out)

VBox(children=(HBox(children=(Dropdown(description='Loss:', options=('CLDICE', 'BCE', 'DICE'), value='CLDICE')…

Output()